"""Create couriers and orders tables

Revision ID: 5a54e28bb136
Revises: 
Create Date: 2024-05-16 00:23:32.494413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5a54e28bb136'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('couriers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('districts', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('active_order', sa.String(), nullable=True),
    sa.Column('avg_order_complete_time', sa.String(), nullable=True),
    sa.Column('avg_day_orders', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couriers_id'), 'couriers', ['id'], unique=False)
    op.create_index(op.f('ix_couriers_name'), 'couriers', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_district'), 'orders', ['district'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_name'), 'orders', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_name'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_district'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_couriers_name'), table_name='couriers')
    op.drop_index(op.f('ix_couriers_id'), table_name='couriers')
    op.drop_table('couriers')
    # ### end Alembic commands ###
